// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourseSystem.Entity
{
    public partial class CourseDatum
    {
        [Key]
        public int Id { get; set; }
        [StringLength(10)]
        public string CourseName { get; set; }
        [StringLength(10)]
        public string TeacherName { get; set; }
        [StringLength(10)]
        public string Time { get; set; }
        [StringLength(10)]
        public string Type { get; set; }
        public long? TeacherId { get; set; }
        [StringLength(10)]
        public string Major { get; set; }
        public int? Score { get; set; }
        [StringLength(100)]
        public string Students { get; set; }
        public int? MaxStuNum { get; set; }
    }
}