// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourseSystem.Entity
{
    [Table("StudentsCourseInfoTable")]
    public partial class StudentsCourseInfoTable
    {
        [Key]
        public int Id { get; set; }
        public long? StudentId { get; set; }
        [StringLength(50)]
        public string ChooseCourse { get; set; }
        public int? CompletedRequiredScore { get; set; }
        public int? ChooseRequiredScore { get; set; }
        public int? CompletedElectiveScore { get; set; }
        public int? ChooseElectiveScore { get; set; }
        public int? CompletedMinorScore { get; set; }
        public int? ChooseMinorScore { get; set; }
    }
}