// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourseSystem.Entity
{
    [Table("StudentInfo")]
    public partial class StudentInfo
    {
        [Key]
        public long Id { get; set; }
        [StringLength(10)]
        public string Name { get; set; }
        [StringLength(10)]
        public string Grade { get; set; }
        [StringLength(10)]
        public string College { get; set; }
        [StringLength(10)]
        public string Major { get; set; }
        [StringLength(10)]
        public string Class { get; set; }
    }
}